# Makefile
#

all:
	gcc -o client client.c
	gcc -o listener listener.c
	gcc -o server server.c
	gcc -o talker talker.c
	gcc -o mp0server mp0server.c
	gcc -o mp0client mp0client.c

clean:
	rm -rf client listener server talker mp0client mp0server
